In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
lista = [i for i in range(5)]

In [8]:
from array import array

In [9]:
import sqlite3

In [10]:
a = array("i",lista)
a

array('i', [0, 1, 2, 3, 4])

In [11]:
a*3

array('i', [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [12]:
matriz = np.array([[1,2],[3,4],[232,6],[123,241]])

In [13]:
print(matriz.dtype)

int32


In [14]:
print(matriz.shape)

(4, 2)


In [15]:
print(matriz)

[[  1   2]
 [  3   4]
 [232   6]
 [123 241]]


In [16]:
arr = np.array([1,4,23,2,6,2,5,14])

In [17]:
fastfood =pd.read_excel("fastfood.xlsx")
fastfood.tail()

restaurant                            item  calories  cal_fat  total_fat  \
510  Taco Bell  Spicy Triple Double Crunchwrap       780      340         38   
511  Taco Bell     Express Taco Salad w/ Chips       580      260         29   
512  Taco Bell          Fiesta Taco Salad-Beef       780      380         42   
513  Taco Bell       Fiesta Taco Salad-Chicken       720      320         35   
514  Taco Bell         Fiesta Taco Salad-Steak       720      320         36   

    sat_fat trans_fat  cholesterol  sodium  total_carb  fiber  sugar  protein  \
510      10       0.5           50    1850          87    9.0      8     23.0   
511       9         1           60    1270          59    8.0      7     23.0   
512      10         1           60    1340          74   11.0      7     26.0   
513       7         0           70    1260          70    8.0      8     32.0   
514       8         1           55    1340          70    8.0      8     28.0   

     vit_a  vit_c  calcium  salad  
510   20.0   10.0     25.0  Other  
511    NaN    NaN      NaN  Other  
512    NaN    NaN      NaN  Other  
513    NaN    NaN      NaN  Other  
514    NaN    NaN      NaN  Other

In [18]:
full = np.full((55,100),5555)
full

array([[5555, 5555, 5555, ..., 5555, 5555, 5555],
       [5555, 5555, 5555, ..., 5555, 5555, 5555],
       [5555, 5555, 5555, ..., 5555, 5555, 5555],
       ...,
       [5555, 5555, 5555, ..., 5555, 5555, 5555],
       [5555, 5555, 5555, ..., 5555, 5555, 5555],
       [5555, 5555, 5555, ..., 5555, 5555, 5555]])

In [19]:
print(arr)

[ 1  4 23  2  6  2  5 14]


In [20]:
np.random.randint(111,3423,size=(10,2))

array([[2608,  837],
       [2260,  614],
       [2682, 1221],
       [2177,  311],
       [2562, 2063],
       [ 913, 1933],
       [2301, 3293],
       [3191, 2422],
       [ 246,  161],
       [1285, 2883]])

In [21]:
arr.sum()

57

In [22]:
df = pd.DataFrame(arr, columns=["notas"])
df

notas
0      1
1      4
2     23
3      2
4      6
5      2
6      5
7     14

In [23]:
pd.Series(arr)

0     1
1     4
2    23
3     2
4     6
5     2
6     5
7    14
dtype: int32

In [24]:
SAL = np.random.randint(0,100,size=(10))
print(SAL)

[38 33 45 33 47 84 43 57 39  1]


In [25]:
print(SAL.dtype)

int32


In [26]:
matuiz = np.random.rand(5,5)
matuiz

array([[0.22670571, 0.91468454, 0.87422535, 0.70044005, 0.59399694],
       [0.33635483, 0.90983827, 0.48961345, 0.34258232, 0.4828837 ],
       [0.32801818, 0.39557226, 0.4774013 , 0.9009833 , 0.09897265],
       [0.38640275, 0.29324066, 0.85232959, 0.54375629, 0.55021892],
       [0.73782901, 0.41623239, 0.32877678, 0.42668224, 0.58408618]])

In [27]:
print("min",matuiz.min())
print("max",matuiz.max())
print("media",matuiz.mean())

min 0.09897264622044633
max 0.9146845367419094
media 0.5276731056004522


In [28]:
NAAA = (np.random.rand(10)*10).astype(int)
print(NAAA)


[5 1 0 7 9 7 6 0 7 4]


In [29]:
SIII = np.random.randint(0,9,size=(3,3))
SIII[1,:]=-1
SIII

array([[ 1,  8,  0],
       [-1, -1, -1],
       [ 4,  4,  3]])

In [30]:
Feira = np.array([[7.90,10.20,11.80],[12,3,4]])
Feira

array([[ 7.9, 10.2, 11.8],
       [12. ,  3. ,  4. ]])

In [31]:
OUTA = pd.DataFrame(Feira)
OUTA

0     1     2
0   7.9  10.2  11.8
1  12.0   3.0   4.0

In [32]:
OUTA = pd.DataFrame(Feira, columns=["Banana","Maça","Pera"], index = ["preço","quantidade"])

OUTA

Banana  Maça  Pera
preço          7.9  10.2  11.8
quantidade    12.0   3.0   4.0

In [33]:
conn = sqlite3.connect("coderhouse.db")

In [34]:
print(conn)

In [35]:
OUTA[OUTA["Banana"]>= 8]

Banana  Maça  Pera
quantidade    12.0   3.0   4.0

In [36]:
conn2 = sqlite3.connect("fastfood.xlsx")
print(conn2)

In [37]:
def tabelas_bd():
    conn2 = sqlite3.connect("Cancer_Data")
    query4 = "SELECT name FROM sqlite_master WHERE type='table'"
    schema = pd.read_sql_query(query4,conn2)
    conn2.close()
    return schema

In [38]:
tabelas_bd()

Empty DataFrame
Columns: [name]
Index: []

In [39]:
def salva_bd(df, nome_tabela):
    conn = sqlite3.connect("coderhouse.db")
    df.to_sql(nome_tabela,conn,if_exists="replace")
    conn.close()
    return df

In [40]:
def carrega_bd(nome_tabela):
    conn = sqlite3.connect("coderhouse.db")
    query = f"SELECT *FROM{nome_tabela}"
    df = pd.read_sql(query,conn)
    conn.close()
    return df

In [43]:
print("count:",OUTA['Banana'].max())

count: 12.0


In [47]:
fastfood = pd.read_excel("fastfood.xlsx")
fastfood.head(3)


restaurant                              item  calories  cal_fat  total_fat  \
0  Mcdonalds  Artisan Grilled Chicken Sandwich       380       60          7   
1  Mcdonalds    Single Bacon Smokehouse Burger       840      410         45   
2  Mcdonalds    Double Bacon Smokehouse Burger      1130      600         67   

  sat_fat            trans_fat  cholesterol  sodium  total_carb  fiber  sugar  \
0       2                    0           95    1110          44    3.0     11   
1      17  2023-05-01 00:00:00          130    1580          62    2.0     18   
2      27                    3          220    1920          63    3.0     18   

   protein  vit_a  vit_c  calcium  salad  
0     37.0    4.0   20.0     20.0  Other  
1     46.0    6.0   20.0     20.0  Other  
2     70.0   10.0   20.0     50.0  Other

In [48]:
fastfood.describe().round(1)

calories  cal_fat  total_fat  cholesterol  sodium  total_carb  fiber  \
count     515.0    515.0      515.0        515.0   515.0       515.0  503.0   
mean      530.9    238.8       26.6         72.5  1246.7        45.7    4.1   
std       282.4    166.4       18.4         63.2   690.0        24.9    3.0   
min        20.0      0.0        0.0          0.0    15.0         0.0    0.0   
25%       330.0    120.0       14.0         35.0   800.0        28.5    2.0   
50%       490.0    210.0       23.0         60.0  1110.0        44.0    3.0   
75%       690.0    310.0       35.0         95.0  1550.0        57.0    5.0   
max      2430.0   1270.0      141.0        805.0  6080.0       156.0   17.0   

       sugar  protein  vit_a  vit_c  calcium  
count  515.0    514.0  301.0  305.0    305.0  
mean     7.3     27.9   18.9   20.2     24.9  
std      6.8     17.7   31.4   30.6     25.5  
min      0.0      1.0    0.0    0.0      0.0  
25%      3.0     16.0    4.0    4.0      8.0  
50%      6.0     24.5   10.0   10.0     20.0  
75%      9.0     36.0   20.0   30.0     30.0  
max     87.0    186.0  180.0  400.0    290.0

In [49]:
fastfood.groupby("restaurant")[["calories"]].mean()

calories
restaurant             
Arbys        532.727273
Burger King  608.571429
Chick Fil-A  384.444444
Dairy Queen  520.238095
Mcdonalds    640.350877
Sonic        631.698113
Subway       503.020833
Taco Bell    443.652174

In [50]:
OUTA.mean()

Banana    9.95
Maça      6.60
Pera      7.90
dtype: float64

In [52]:
OUTA["Banana"].mean()

9.95

In [58]:
OUTA.groupby("Maça").median()

Banana  Pera
Maça              
3.0     12.0   4.0
10.2     7.9  11.8

In [66]:
OUTA.groupby("Pera").agg(["min","max"]).round()

Banana        Maça      
        min   max   min   max
Pera                         
4.0    12.0  12.0   3.0   3.0
11.8    8.0   8.0  10.0  10.0

In [67]:
OUTA.sort_values("Banana")

Banana  Maça  Pera
preço          7.9  10.2  11.8
quantidade    12.0   3.0   4.0

In [70]:
pd.concat([OUTA,fastfood], ignore_index = True)

Banana  Maça  Pera restaurant                              item  \
0       7.9  10.2  11.8        NaN                               NaN   
1      12.0   3.0   4.0        NaN                               NaN   
2       NaN   NaN   NaN  Mcdonalds  Artisan Grilled Chicken Sandwich   
3       NaN   NaN   NaN  Mcdonalds    Single Bacon Smokehouse Burger   
4       NaN   NaN   NaN  Mcdonalds    Double Bacon Smokehouse Burger   
..      ...   ...   ...        ...                               ...   
512     NaN   NaN   NaN  Taco Bell    Spicy Triple Double Crunchwrap   
513     NaN   NaN   NaN  Taco Bell       Express Taco Salad w/ Chips   
514     NaN   NaN   NaN  Taco Bell            Fiesta Taco Salad-Beef   
515     NaN   NaN   NaN  Taco Bell         Fiesta Taco Salad-Chicken   
516     NaN   NaN   NaN  Taco Bell           Fiesta Taco Salad-Steak   

     calories  cal_fat  total_fat sat_fat            trans_fat  cholesterol  \
0         NaN      NaN        NaN     NaN                  NaN          NaN   
1         NaN      NaN        NaN     NaN                  NaN          NaN   
2       380.0     60.0        7.0       2                    0         95.0   
3       840.0    410.0       45.0      17  2023-05-01 00:00:00        130.0   
4      1130.0    600.0       67.0      27                    3        220.0   
..        ...      ...        ...     ...                  ...          ...   
512     780.0    340.0       38.0      10                  0.5         50.0   
513     580.0    260.0       29.0       9                    1         60.0   
514     780.0    380.0       42.0      10                    1         60.0   
515     720.0    320.0       35.0       7                    0         70.0   
516     720.0    320.0       36.0       8                    1         55.0   

     sodium  total_carb  fiber  sugar  protein  vit_a  vit_c  calcium  salad  
0       NaN         NaN    NaN    NaN      NaN    NaN    NaN      NaN    NaN  
1       NaN         NaN    NaN    NaN      NaN    NaN    NaN      NaN    NaN  
2    1110.0        44.0    3.0   11.0     37.0    4.0   20.0     20.0  Other  
3    1580.0        62.0    2.0   18.0     46.0    6.0   20.0     20.0  Other  
4    1920.0        63.0    3.0   18.0     70.0   10.0   20.0     50.0  Other  
..      ...         ...    ...    ...      ...    ...    ...      ...    ...  
512  1850.0        87.0    9.0    8.0     23.0   20.0   10.0     25.0  Other  
513  1270.0        59.0    8.0    7.0     23.0    NaN    NaN      NaN  Other  
514  1340.0        74.0   11.0    7.0     26.0    NaN    NaN      NaN  Other  
515  1260.0        70.0    8.0    8.0     32.0    NaN    NaN      NaN  Other  
516  1340.0        70.0    8.0    8.0     28.0    NaN    NaN      NaN  Other  

[517 rows x 20 columns]

In [75]:
df4 = pd.DataFrame({"A":[4,2,1,3],"B":["a","b","c","b"]})
df5 = pd.DataFrame({"A":[2,3,5],"C":[10,20,30]})

In [80]:
df4.merge(df5,on="A",how = "inner")

A  B   C
0  2  b  10
1  3  b  20

In [81]:
df4.merge(df5,on="A",how = "left")

A  B     C
0  4  a   NaN
1  2  b  10.0
2  1  c   NaN
3  3  b  20.0

In [82]:
df4.merge(df5,on="A",how = "right")

A    B   C
0  2    b  10
1  3    b  20
2  5  NaN  30

In [85]:
df4.merge(df5,on="A",how = "outer")


A    B     C
0  4    a   NaN
1  2    b  10.0
2  1    c   NaN
3  3    b  20.0
4  5  NaN  30.0

In [86]:
pd.concat([df4,df5], axis = 1)

A  B    A     C
0  4  a  2.0  10.0
1  2  b  3.0  20.0
2  1  c  5.0  30.0
3  3  b  NaN   NaN

In [89]:
df4.groupby("B").sum("A")

A
B   
a  4
b  5
c  1